services:
  
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/mydb # MONGO_URI=mongodb://<user>:<pass>@<host>:27017/db
      # MONGO_URI=mongodb://bbuser:bbpassword@192.168.245.106:27017/bloodbank
      - JWT_SECRET=secret
    depends_on: 
      - mongodb

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
